//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_dienthoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietSP()
        {
            this.ChiTietDH = new HashSet<ChiTietDH>();
        }
    
        public string MaCTSP { get; set; }
        public string MaSP { get; set; }
        public string MaDL { get; set; }
        public string MaMau { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<int> SoLuongKho { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDH> ChiTietDH { get; set; }
        public virtual DungLuong DungLuong { get; set; }
        public virtual Mau Mau { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
