//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_dienthoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDH
    {
        public string MaCTDH { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> GiaMua { get; set; }
        public Nullable<int> Thanhtien { get; set; }
        public string MaCTSP { get; set; }
        public string MaDH { get; set; }
    
        public virtual ChiTietSP ChiTietSP { get; set; }
        public virtual DonHang DonHang { get; set; }
    }
}
