//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_dienthoai.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLDienThoaiEntities : DbContext
    {
        public QLDienThoaiEntities()
            : base("name=QLDienThoaiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<ChiTietDH> ChiTietDH { get; set; }
        public virtual DbSet<ChiTietSP> ChiTietSP { get; set; }
        public virtual DbSet<DonHang> DonHang { get; set; }
        public virtual DbSet<DungLuong> DungLuong { get; set; }
        public virtual DbSet<HinhSP> HinhSP { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<LoaiKH> LoaiKH { get; set; }
        public virtual DbSet<Mau> Mau { get; set; }
        public virtual DbSet<SanPham> SanPham { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TSKTSP> TSKTSP { get; set; }
        public virtual DbSet<ThuongHieu> ThuongHieu { get; set; }
    }
}
