//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_dienthoai.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLDienThoaiEntities : DbContext
    {
        public QLDienThoaiEntities()
            : base("name=QLDienThoaiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<BinhLuan> BinhLuan { get; set; }
        public virtual DbSet<ChiTietDH> ChiTietDH { get; set; }
        public virtual DbSet<ChiTietSP> ChiTietSP { get; set; }
        public virtual DbSet<DonHang> DonHang { get; set; }
        public virtual DbSet<DungLuong> DungLuong { get; set; }
        public virtual DbSet<GiamGiaSP> GiamGiaSP { get; set; }
        public virtual DbSet<HinhSP> HinhSP { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<LoaiKH> LoaiKH { get; set; }
        public virtual DbSet<Mau> Mau { get; set; }
        public virtual DbSet<PhieuGiamGia> PhieuGiamGia { get; set; }
        public virtual DbSet<SanPham> SanPham { get; set; }
        public virtual DbSet<TSKTSP> TSKTSP { get; set; }
        public virtual DbSet<ThuongHieu> ThuongHieu { get; set; }
    
        public virtual int SLSPban(string tensp, ObjectParameter sl)
        {
            var tenspParameter = tensp != null ?
                new ObjectParameter("tensp", tensp) :
                new ObjectParameter("tensp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SLSPban", tenspParameter, sl);
        }
    
        public virtual int ThemCTDH(string mactdh, Nullable<int> sl, Nullable<int> thanhtien, string mactsp, string madh, Nullable<int> giamua)
        {
            var mactdhParameter = mactdh != null ?
                new ObjectParameter("mactdh", mactdh) :
                new ObjectParameter("mactdh", typeof(string));
    
            var slParameter = sl.HasValue ?
                new ObjectParameter("sl", sl) :
                new ObjectParameter("sl", typeof(int));
    
            var thanhtienParameter = thanhtien.HasValue ?
                new ObjectParameter("thanhtien", thanhtien) :
                new ObjectParameter("thanhtien", typeof(int));
    
            var mactspParameter = mactsp != null ?
                new ObjectParameter("mactsp", mactsp) :
                new ObjectParameter("mactsp", typeof(string));
    
            var madhParameter = madh != null ?
                new ObjectParameter("madh", madh) :
                new ObjectParameter("madh", typeof(string));
    
            var giamuaParameter = giamua.HasValue ?
                new ObjectParameter("giamua", giamua) :
                new ObjectParameter("giamua", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemCTDH", mactdhParameter, slParameter, thanhtienParameter, mactspParameter, madhParameter, giamuaParameter);
        }
    
        public virtual int ThemDH(string madh, string makh, string tennn, string sdt, string diachi, Nullable<int> trigia, string httt, string htgh, Nullable<int> tongtien)
        {
            var madhParameter = madh != null ?
                new ObjectParameter("madh", madh) :
                new ObjectParameter("madh", typeof(string));
    
            var makhParameter = makh != null ?
                new ObjectParameter("makh", makh) :
                new ObjectParameter("makh", typeof(string));
    
            var tennnParameter = tennn != null ?
                new ObjectParameter("tennn", tennn) :
                new ObjectParameter("tennn", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var trigiaParameter = trigia.HasValue ?
                new ObjectParameter("trigia", trigia) :
                new ObjectParameter("trigia", typeof(int));
    
            var htttParameter = httt != null ?
                new ObjectParameter("httt", httt) :
                new ObjectParameter("httt", typeof(string));
    
            var htghParameter = htgh != null ?
                new ObjectParameter("htgh", htgh) :
                new ObjectParameter("htgh", typeof(string));
    
            var tongtienParameter = tongtien.HasValue ?
                new ObjectParameter("tongtien", tongtien) :
                new ObjectParameter("tongtien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemDH", madhParameter, makhParameter, tennnParameter, sdtParameter, diachiParameter, trigiaParameter, htttParameter, htghParameter, tongtienParameter);
        }
    
        public virtual int ThemKH(string makh, string tenkh, string sdt, string diachi, string gioitinh, Nullable<System.DateTime> ngaysinh, string mk, string email)
        {
            var makhParameter = makh != null ?
                new ObjectParameter("makh", makh) :
                new ObjectParameter("makh", typeof(string));
    
            var tenkhParameter = tenkh != null ?
                new ObjectParameter("tenkh", tenkh) :
                new ObjectParameter("tenkh", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var mkParameter = mk != null ?
                new ObjectParameter("mk", mk) :
                new ObjectParameter("mk", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemKH", makhParameter, tenkhParameter, sdtParameter, diachiParameter, gioitinhParameter, ngaysinhParameter, mkParameter, emailParameter);
        }
    
        public virtual int ThemPhieuGiamGia(string tengiamgia, Nullable<int> chietkhau)
        {
            var tengiamgiaParameter = tengiamgia != null ?
                new ObjectParameter("tengiamgia", tengiamgia) :
                new ObjectParameter("tengiamgia", typeof(string));
    
            var chietkhauParameter = chietkhau.HasValue ?
                new ObjectParameter("chietkhau", chietkhau) :
                new ObjectParameter("chietkhau", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemPhieuGiamGia", tengiamgiaParameter, chietkhauParameter);
        }
    
        public virtual int XoaDH(string madh)
        {
            var madhParameter = madh != null ?
                new ObjectParameter("madh", madh) :
                new ObjectParameter("madh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaDH", madhParameter);
        }
    
        public virtual int XoaDH_SDT(string sdt)
        {
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaDH_SDT", sdtParameter);
        }
    
        public virtual int XoaKH(string sdt)
        {
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaKH", sdtParameter);
        }
    
        public virtual int XoaPhieuGG(Nullable<int> maphieugg)
        {
            var maphieuggParameter = maphieugg.HasValue ?
                new ObjectParameter("maphieugg", maphieugg) :
                new ObjectParameter("maphieugg", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaPhieuGG", maphieuggParameter);
        }
    }
}
